### ISSUE TITLE
Just wondering

### ISSUE THREAD

**Issue by mikecann** [get-convex/workpool#6]
Hey @ldanilek I was just looking through the code and just interested to hear about your thoughts around the choices in https://github.com/get-convex/workpool/blob/main/src/component/schema.ts

Im just wondering if there is a particular reason why multiple tables are used to define the "status" of a job in the pool?

```ts
  pendingWork: defineTable({
    fnType: v.union(
      v.literal("action"),
      v.literal("mutation"),
      v.literal("unknown")
    ),
    fnHandle: v.string(),
    fnName: v.string(),
    fnArgs: v.any(),
    runAtTime: v.number(),
  }).index("runAtTime", ["runAtTime"]),
  
 pendingCompletion: defineTable({
    result: v.optional(v.any()),
    error: v.optional(v.string()),
    workId: v.id("pendingWork"),
  }).index("workId", ["workId"]),
  pendingCancelation: defineTable({
    workId: v.id("pendingWork"),
  }),

  inProgressWork: defineTable({
    running: v.id("_scheduled_functions"),
    timeoutMs: v.number(),
    workId: v.id("pendingWork"),
  }).index("workId", ["workId"]),

  completedWork: defineTable({
    result: v.optional(v.any()),
    error: v.optional(v.string()),
    workId: v.id("pendingWork"),
  }).index("workId", ["workId"]),
```

The way I have been doing it up to now is by having a single field that represents the status so instead of the above on my personal projects I have been doing something like the following:

```ts
workItem: defineTable({
  fnType: v.union(
    v.literal("action"),
    v.literal("mutation"),
    v.literal("unknown")
  ),
  fnHandle: v.string(),
  fnName: v.string(),
  fnArgs: v.any(),
  status: v.union(
    v.object({
      kind: v.literal("pending_start"),
      runAtTime: v.number(),
    }),
    v.object({
      kind: v.literal("pending_completion"),
      result: v.optional(v.any()),
      error: v.optional(v.string()),
      timeoutMs: v.number(),
    }),
    v.object({
      kind: v.literal("pending_cancelation"),
    }),
    v.object({
      kind: v.literal("in_progress"),
      running: v.id("_scheduled_functions"),
      timeoutMs: v.number(),
    }),
    v.object({
      kind: v.literal("completed"),
      result: v.optional(v.any()),
      error: v.optional(v.string()),
    }),
  )
})
```

Just interested if I have been doing it wrong or if there is a better reason to separate things out into separate tables?

**Comment by ldanilek** [comment]
It's designed like this to allow read and write patterns that minimize overlaps. If reads and writes don't overlap, they can be done in mutations that run in parallel (this is a general property of transactions). 

e.g. when something is scheduled, it's inserted with status "pending_start" and a large runAtTime. When we're deciding what to run, we look at work with status of "pending_start" and low runAtTime. This means we can schedule things in parallel with running them. But to make this work, the runner needs to avoid looking at work with high runAtTime, and it should also avoid looking at completed work -- because if you look at completed work then you can't kick off work in parallel with work completions. 

Despite all that, this repo has only one pattern. You can make do with one table with some clever indexes, or you can have a completely different workpool design like https://stack.convex.dev/work-stealing , or if your workpool doesn't need high throughput you can do whatever you want.

**Comment by mikecann** [comment]
Ahh I see okay, yes I guess high throughput is going to be very important for this component. 

Makes sense, thanks :)
